volumes:

  postgres_volume:

services:
  server_pg:
    image: postgres:14-alpine3.17
    container_name: server_pg
    env_file:
      - local.env
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - server_pg  
  server_migrator:
    container_name: server_migrator
    image: ${MIGRATOR_IMAGE}
    build:
      context: .
      dockerfile: migrator-local.Dockerfile
    restart: on-failure
    networks:
      - server_pg
networks:
  server_pg:      