name: Reusable PG Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      env_file_content:
        required: true
        type: string
      docker_compose_file:
        required: true
        type: string
      image_name:
        required: true
        type: string
    secrets:
      SERVER_HOST:
        required: true
      SSH_USERNAME:
        required: true
      SSHKEY:
        required: true
      DOCKER_REGISTRY_USERNAME:
        required: true
      DOCKER_REGISTRY_PASSWORD:
        required: true

env:
  DOCKER_REGISTRY_URL: cr.selcloud.ru/mfisher1411
  DB_DIR: week_2/config

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.meta.outputs.tag }}

    steps:
      - uses: actions/checkout@v3

      - name: Write env file
        run: |
          echo "${{ inputs.env_file_content }}" > ${{ env.DB_DIR }}/${{ inputs.environment }}.env

      - name: Setup Docker tag
        id: meta
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Setup image name
        run: |
          echo "MIGRATOR_IMAGE=${{ env.DOCKER_REGISTRY_URL }}/${{ inputs.image_name }}:${{ steps.meta.outputs.tag }}" >> "$GITHUB_ENV"

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: docker compose -f ${{ env.DB_DIR }}/${{ inputs.docker_compose_file }} build

      - name: Push Docker image
        run: docker image push ${{ env.MIGRATOR_IMAGE }}

      - name: Generate .env file
        run: |
          echo "# Autogenerated .env file" > ${{ env.DB_DIR }}/.env
          echo "MIGRATOR_IMAGE=${{ env.MIGRATOR_IMAGE }}" >> ${{ env.DB_DIR }}/.env

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: 22
          source: "${{ env.DB_DIR }}/${{ inputs.docker_compose_file }},${{ env.DB_DIR }}/${{ inputs.environment }}.env,${{ env.DB_DIR }}/.env"
          target: "~/.deploy/"

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: 22
          script: |
            docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }} ${{ env.DOCKER_REGISTRY_URL }}
            cd ~/.deploy/${{ env.DB_DIR }}
            docker compose -f ./${{ inputs.docker_compose_file }} up -d
