name: week_2_pg_prod

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-deploy:
    uses: ./.github/workflows/reusable_pg_deploy.yaml
    with:
      environment: prod
      env_file_content: ${{ secrets.PG_PROD_ENV_FILE }}
      docker_compose_file: docker-compose.prod.yaml
      image_name: week_2_pg_prod
    secrets:
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSHKEY: ${{ secrets.SSHKEY }}
      DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
