name: DB
on:
  push:
    branches:
      - main 

  pull_request:
    branches:
      - main    


env:
  DB_DIR: week_2/postgres
  MIGRATOR_IMAGE_NAME: server_migrator
  DOCKER_REGISTRY_URL: cr.selcloud.ru/mfisher1411

jobs:
  build-and-push:
    name: Build and Push migrator
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.meta.outputs.tag }}
    steps:
      - uses: actions/checkout@v3

      - name: Create .env file
        run: |
          touch ${{ env.DB_DIR }}/.env
          echo "${{ secrets.POSTGRES_ENV_FILE }}" > ${{ env.DB_DIR }}/.env

      - name: Setup Docker Tag
        id: meta
        run: |
          echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Setup Image names
        run: |
          echo "MIGRATOR_IMAGE=${{ env.DOCKER_REGISTRY_URL }}/${{ env.MIGRATOR_IMAGE_NAME }}:${{ steps.meta.outputs.tag }}" >> "$GITHUB_ENV"

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{env.DOCKER_REGISTRY_URL}}
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}

      - name: Build migrator
        run: |
          docker compose -f ${{ env.DB_DIR }}/docker-compose.yaml build

      - name: Push migrator to registry
        if: ${{ github.event_name != 'pull_request'}}
        run: docker image push ${{ env.MIGRATOR_IMAGE }}

  deploy:
    name: Deploy DB and Migrate on Selectel Cloud
    if: ${{ github.event_name != 'pull_request'}}
    runs-on: ubuntu-latest
    needs:
      - build-and-push
    steps:
      - uses: actions/checkout@v3

      - name: Create prod.env file
        run: |
          touch ${{ env.DB_DIR }}/.env
          echo "${{ secrets.POSTGRES_ENV_FILE }}" > ${{ env.DB_DIR }}/.env

      - name: Create .env file
        run: |
          echo "Generating .env file"
          
          echo "# Autogenerated .env file" > ${{ env.DB_DIR }}/.env
          echo "MIGRATOR_IMAGE=${{ env.DOCKER_REGISTRY_URL }}/${{ env.MIGRATOR_IMAGE_NAME }}:${{ needs.build-and-push.outputs.tag }}" >> ${{ env.DB_DIR }}/.env

      - name: Send docker compose to Selectel server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{secrets.SSH_USERNAME}}
          port: 22
          key: ${{secrets.SSHKEY}}
          source: "${{ env.DB_DIR }}/docker-compose.yaml,${{ env.DB_DIR }}/.env,${{ env.DB_DIR }}/.env"
          target: "~/.deploy/"

      - name: Run DB and Migrate
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSHKEY}}
          port: 22
          envs: APPTOKEN,USERNAME
          script: |
            # Login into Selectel Registry
            docker login -u ${{secrets.REGISTRY_USERNAME}} -p ${{secrets.REGISTRY_PASSWORD}} ${{env.DOCKER_REGISTRY_URL}}
            cd ~/.deploy/${{ env.DB_DIR }}
            docker-compose -f ./docker-compose.yaml up -d